Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
