Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
