checks:
  ruby: true
  javascript: true
filter:
  excluded_paths:
    - 'test/*'
    - 'vendor/*'
build:
  tests:
    override:
      -
        command: 'bundle exec rake test'
        environment: 'SCRUTINIZER_CC_FILE': 'code-coverage'
        coverage:
          file: 'code-coverage'
          format: 'rb-cc'

