checks:
  ruby: true
  javascript: true
filter:
  excluded_paths:
    - 'test/*'
    - 'vendor/*'
build:
  environment:
    ruby: '2.3.1'
  tests:
    before:
      - 'cp ./config/database.yml.example ./config/database.yml'
      - 'cp ./config/secrets.yml.example ./config/secrets.yml'
    override:
      -
        command: 'bundle exec rake test'
        environment:
          'SCRUTINIZER_CC_FILE': 'code-coverage'
        coverage:
          file: 'code-coverage'
          format: 'rb-cc'

