version: "3.4"

services:
  app:
    image: "c3boc/c3bos:35c3-0.8"
    environment:
      RAILS_ENV: "production"
      DATABASE_PASSWORD: "example"
      SECRET_KEY_BASE: "example"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:c3boc.de"
  db:
    image: "postgres:11.1"
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "c3bos"
      POSTGRES_USER: "c3bos"
    volumes:
      - db:/var/lib/postgresql/data
  proxy:
    image: traefik:1.6.5
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/traefik.toml:/traefik.toml
      - /etc/traefik/acme.json:/acme.json
    networks:
      - default
      - proxy
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:traefik.c3boc.de"
        - "traefik.frontend.auth.basic=gnomus:$$apr1$$kARkJ8q/$$0tG8RtmbdcbL5We0N1aCp/"

networks:
  default:
  proxy:
    internal: true

volumes:
  db:
