version: "3.4"

services:
  app:
    image: "bos:3"
    environment:
      RAILS_ENV: "production"
      DATABASE_PASSWORD: "example"
      SECRET_KEY_BASE: "example1234"
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    networks:
      - default
      - db
  db:
    image: "postgres:11.1"
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "c3bos"
      POSTGRES_USER: "c3bos"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
  print:
    restart: always
    image: "print:9"
    devices:
      - /dev/usb/lp0:/dev/usb/lp0
    


networks:
  default:
  db:
    internal: true

volumes:
  db:
