version: 2
jobs:
  rubocop:
    docker:
      - image: ruby:2.5.3
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
  unittests:
    docker:
      - image: ruby:2.5.3
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec test
workflows:
  version: 2
  lint:
    jobs:
      - rubocop
  test:
    jobs:
      - unittests
