version: 2
jobs:
  deps:
    docker:
      - image: ruby:2.5.3
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-install-{{ checksum "Gemfile.lock" }}
            - v1-bundle-install-
      - run: find vendor
      - run:
          name: Bundler install
          command: bundle install
      - save_cache:
          key: v1-bundle-install-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Setup database.yml
          command: cp config/database.yml.example config/database.yml
      - persist_to_workspace:
          root: /root/project/
          paths:
            - vendor/bundle
            - config/database.yml
  rubocop:
    docker:
      - image: ruby:2.5.3
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: run rubocop
          command: bundle exec rubocop
  unittests:
    docker:
      - image: ruby:2.5.3
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: postgres:11
        environment:
          POSTGRES_DB: c3bos_test
          POSTGRES_USER: c3bos_test
          POSTGRES_PASSWORD: c3bos_test
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Run tests
          command: bundle exec rake test
workflows:
  version: 2
  test:
    jobs:
      - deps
#      - unittests:
#          requires:
#            - deps
      - rubocop:
          requires:
            - deps
