version: 2
jobs:
  rubocop:
    docker:
      - image: ruby:2.5.3
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
  unittests:
    docker:
      - image: ruby:2.5.3
      - image: postgres:10.1
    steps:
      - checkout
      - run: bundle install
      - run: cp config/database.yml.example config/database.yml
      - run: bundle exec rake test
workflows:
  version: 2
  lint:
    jobs:
      - rubocop
  test:
    jobs:
      - unittests
