version: 2
jobs:
  rubocop:
    docker:
      - image: ruby:2.5.3
    steps:
      - checkout 
      - run: bundle install
      - run: bundle exec rubocop
workflows:
  version: 2
  lint:
    jobs:
      - rubocop
